Repository jupyter-server/jupyter_ydoc, pull requests merged in 2022-11, with the labels that each got.

#89 Fix export to respect ESM syntax
  .gitignore
  javascript/babel.config.cjs
  javascript/jest.config.cjs
  javascript/package.json
  javascript/src/api.ts
  javascript/src/index.ts
  javascript/src/utils.ts
  javascript/src/ymodels.ts
  javascript/test/ymodels.spec.ts
  javascript/tsconfig.test.json
  javascript/yarn.lock
Labels: maintenance

#88 Backport PR #86 on branch main (Import shared model)
  .github/workflows/test.yml
  .gitignore
  CHANGELOG.md
  javascript/.eslintignore
  javascript/.eslintrc.cjs
  javascript/.prettierignore
  javascript/.prettierrc
  javascript/.vscode/launch.json
  javascript/jest.config.cjs
  javascript/package.json
  javascript/src/api.ts
  javascript/src/index.ts
  javascript/src/utils.ts
  javascript/src/ymodels.ts
  javascript/test/ymodels.spec.ts
  javascript/tsconfig.json
  javascript/tsconfig.test.json
  javascript/typedoc.json
  javascript/yarn.lock
  tests/conftest.py
  tests/package.json
  tests/yjs_client_0.js
Labels: enhancement, api-change

#90 Releaser
  .github/workflows/check-release.yml
  .github/workflows/enforce-label.yml
  .gitignore
  javascript/package.json
  jupyter_ydoc/__init__.py
  package.json
  pyproject.toml
Labels: maintenance

#95 Documentation
  .gitignore
  docs/Makefile
  docs/make.bat
  docs/source/_static/jupyter_logo.svg
  docs/source/_static/logo-icon.png
  docs/source/api/index.html
  docs/source/changelog.md
  docs/source/conf.py
  docs/source/custom.md
  docs/source/index.md
  docs/source/javascript_api.rst
  docs/source/overview.md
  docs/source/python_api.rst
  docs/source/schema.md
  javascript/.eslintignore
  javascript/.prettierignore
  javascript/package.json
  javascript/yarn.lock
  jupyter_ydoc/ydoc.py
  pyproject.toml
  readthedocs.yml
Labels: documentation

#92 Backport #90 on branch main (Releaser)
  .github/workflows/check-release.yml
  .gitignore
  javascript/package.json
  jupyter_ydoc/__init__.py
  package.json
  pyproject.toml
Labels: maintenance

#97 Rename JS package to `@jupyter/ydoc`
  javascript/package.json
  javascript/test/ymodels.spec.ts
  package.json
  tests/package.json
  tests/yjs_client_0.js
Labels: maintenance

#104 Backport PR #97 on branch 0.2.x (Rename JS package to @jupyter/ydoc)
  javascript/package.json
  javascript/test/ymodels.spec.ts
  package.json
  tests/package.json
  tests/yjs_client_0.js
Labels: maintenance

#105 Add badges
  README.md
Labels: documentation

#106 Add readme to javascript package
  javascript/README.md
Labels: enhancement

#101 Adds docstring to the python package
  jupyter_ydoc/ydoc.py
Labels: documentation, enhancement
