Repository jupyter-server/jupyter_ydoc, pull requests merged in 2023-02, with the labels that each got.

#142 Update `YDocument` constructor
  javascript/src/ydocument.ts
Labels: enhancement, maintenance

#145 Update with ypy v0.6.0
  jupyter_ydoc/ynotebook.py
  pyproject.toml
Labels: maintenance

#147 Workaround for ypy 0.6.0
  jupyter_ydoc/ynotebook.py
Labels: bug

#148 Fix notebook undo scope
  .github/workflows/test.yml
  javascript/src/api.ts
  javascript/src/ycell.ts
  javascript/test/ycell.spec.ts
  javascript/test/ynotebook.spec.ts
Labels: bug

#150 Add releaser workflows
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  pyproject.toml
Labels: maintenance

#149 Backport PR #148 on branch 0.2.x (Fix notebook undo scope)
  .github/workflows/test.yml
  .pre-commit-config.yaml
  javascript/src/api.ts
  javascript/src/ymodels.ts
  javascript/test/ycell.spec.ts
  javascript/test/ymodels.spec.ts
  tests/conftest.py
Labels: bug
