Repository jupyter-server/jupyter_ydoc, pull requests merged in 2023-01, with the labels that each got.

#115 Notebook metadata
  .github/workflows/license-header.yml
  javascript/src/api.ts
  javascript/src/index.ts
  javascript/src/ycell.ts
  javascript/src/ydocument.ts
  javascript/src/yfile.ts
  javascript/src/ynotebook.ts
  javascript/src/ytext.ts
  javascript/test/ymodels.spec.ts
  jupyter_ydoc/ydoc.py
  package.json
Labels: enhancement

#119 Set up lerna
  docs/Makefile
  docs/make.bat
  docs/source/api/index.html
  docs/source/conf.py
  docs/source/javascript_api.rst
  docs/source/python_api.rst
  javascript/yarn.lock
  jupyter_ydoc/__init__.py
  jupyter_ydoc/utils.py
  jupyter_ydoc/ydoc.py
  lerna.json
  package.json
  pyproject.toml
  pytest.ini
  tests/conftest.py
  tests/package.json
  tests/test_ypy_yjs.py
  tests/yjs_client_0.js
  yarn.lock
Labels: maintenance

#120 Fixes metadata
  .licenserc.yaml
  javascript/src/ynotebook.ts
  yarn.lock
Labels: bug

#124 Improves the initialization
  javascript/src/api.ts
  javascript/src/ynotebook.ts
  javascript/test/ymodels.spec.ts
  jupyter_ydoc/ydoc.py
Labels: enhancement

#125 Adds the API for a ISharedDocument factory
  .github/workflows/test.yml
  javascript/src/api.ts
Labels: enhancement

#122 Improve Python API
  README.md
  jupyter_ydoc/ydoc.py
  pyproject.toml
Labels: enhancement

#126 docs: small README typo fix
  README.md
Labels: maintenance

#127 Import all document types from __init__
  jupyter_ydoc/__init__.py
Labels: maintenance

#129 Improve IFactory API
  javascript/src/api.ts
  yarn.lock
Labels: enhancement

#131 Fixes multiple bugs
  javascript/package.json
  javascript/src/api.ts
  javascript/src/ycell.ts
  javascript/src/yfile.ts
  javascript/src/ynotebook.ts
  javascript/test/ycell.spec.ts
  javascript/test/yfile.spec.ts
  javascript/test/ynotebook.spec.ts
  yarn.lock
Labels: bug, dependencies, api-change

#132 Integrity check
  .github/workflows/test.yml
  javascript/package.json
  yarn.lock
Labels: maintenance

#133 Remove factory API
  docs/source/custom.md
  javascript/src/api.ts
Labels: enhancement, api-change

#134 Fixes handling metadata changes
  javascript/src/ynotebook.ts
Labels: bug

#135 Split documents into separate files
  README.md
  jupyter_ydoc/__init__.py
  jupyter_ydoc/ybasedoc.py
  jupyter_ydoc/yblob.py
  jupyter_ydoc/yfile.py
  jupyter_ydoc/ynotebook.py
  jupyter_ydoc/yunicode.py
  pyproject.toml
Labels: enhancement, maintenance

#136 Add ycells getter
  jupyter_ydoc/ynotebook.py
Labels: enhancement, maintenance
