Repository jupyter-server/jupyter_ydoc, pull requests merged in 2023-03, with the labels that each got.

#151 Bump dependencies and yarn
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .yarn/releases/yarn-3.4.1.cjs
  .yarnrc.yml
  javascript/jest.config.cjs
  javascript/package.json
  javascript/src/ycell.ts
  javascript/src/ydocument.ts
  javascript/src/ynotebook.ts
  javascript/test/ycell.spec.ts
  javascript/test/ynotebook.spec.ts
  package.json
  tests/conftest.py
  tests/package.json
  tests/test_ypy_yjs.py
  yarn.lock
Labels: maintenance

#139 Add model version
  javascript/src/api.ts
  javascript/src/ydocument.ts
  javascript/src/yfile.ts
  javascript/src/ynotebook.ts
  jupyter_ydoc/ybasedoc.py
  jupyter_ydoc/yblob.py
  jupyter_ydoc/ynotebook.py
  jupyter_ydoc/yunicode.py
Labels: enhancement

#152 Add py.typed
  .licenserc.yaml
  jupyter_ydoc/py.typed
Labels: enhancement, maintenance

#154 Enhance the documentation
  .github/workflows/check-release.yml
  .gitignore
  docs/source/api/index.html
  docs/source/changelog.md
  docs/source/conf.py
  docs/source/python_api.rst
  javascript/package.json
  javascript/typedoc.json
Labels: documentation

#155 Fix ignore_links
  .github/workflows/check-release.yml
Labels: documentation
