Repository jupyter-server/jupyter_ydoc, pull requests merged in 2024-10, with the labels that each got.

#277 Doc awareness
  jupyter_ydoc/ybasedoc.py
  jupyter_ydoc/yblob.py
  jupyter_ydoc/ynotebook.py
  jupyter_ydoc/yunicode.py
  pyproject.toml
  tests/test_ydocs.py
Labels: enhancement, Still Needs Manual Backport

#279 Backport PR #277: Doc awareness
  jupyter_ydoc/ybasedoc.py
  jupyter_ydoc/yblob.py
  jupyter_ydoc/ynotebook.py
  jupyter_ydoc/yunicode.py
  pyproject.toml
  tests/test_ydocs.py
Labels: maintenance

#280 Revert #266
  jupyter_ydoc/ynotebook.py
Labels: maintenance

#282 Add the awareness in the shared document interface
  javascript/src/api.ts
Labels: enhancement

#283 Backport PR #282: Add the awareness in the shared document interface
  javascript/src/api.ts
Labels: maintenance
